[project]
name = "nkmt_v1"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.level-i]
path = "contracts/level-i.clar"

[contracts.level-ii]
path = "contracts/level-ii.clar"

[contracts.level-iii]
path = "contracts/level-iii.clar"

[contracts.level-iv]
path = "contracts/level-iv.clar"

[contracts.sip-09]
path = "contracts/sip-09.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
