[project]
name = 'Nakamoto_1'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'
requirements = []
[contracts.DROID]
path = 'contracts/DROID.clar'
clarity_version = 2
epoch = 2.5

[contracts.Nakamoto_1_Android]
path = 'contracts/Nakamoto_1_Android.clar'
clarity_version = 1
epoch = 2.05

[contracts.Nakamoto_1_Gold_Android]
path = 'contracts/Nakamoto_1_Gold_Android.clar'
clarity_version = 1
epoch = 2.05

[contracts.Nakamoto_1_Level_1]
path = 'contracts/Nakamoto_1_Level_1.clar'
clarity_version = 1
epoch = 2.05

[contracts.Nakamoto_1_Level_2]
path = 'contracts/Nakamoto_1_Level_2.clar'
clarity_version = 1
epoch = 2.05

[contracts.sip-09]
path = 'contracts/sip-09.clar'
clarity_version = 1
epoch = 2.05
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
