[project]
name = "Nakamoto_1"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"

[contracts.Nakamoto_1_Level_1]
path = "contracts/Nakamoto_1_Level_1.clar"

[contracts.Nakamoto_1_Level_2]
path = "contracts/Nakamoto_1_Level_2.clar"

[contracts.Nakamoto_1_Android]
path = "contracts/Nakamoto_1_Android.clar"

[contracts.Nakamoto_1_Gold_Android]
path = "contracts/Nakamoto_1_Gold_Android.clar"

[contracts.sip-09]
path = "contracts/sip-09.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
